[tool.poetry]
name = "llm-app"
version = "0.1.0"
description = ""
authors = ["k-natori1025 <k-natori1025@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "1.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
